export const CONCLUSION_EXAMPLES = {
    example1: `Conclusie en advies
  Op basis van de resultaten tijdens het assessment center, de psychologische test en de interviews, komen wij tot de volgende conclusie.
  De heer Van der Corput laat gedurende het assessment zien over de nodige talenten te beschikken. Hij is een mensen-mens die zeer gemakkelijk contact maakt en een gun factor heeft. Van nature neemt hij de leiding op zich, is proactief en consciëntieus. Met veel flair en opgewektheid heeft hij een enthousiasmerende uitstraling. Hij beschikt over een can do mentaliteit, treedt zonder veel schroom op de voorgrond en is kritisch op zichzelf.
  Hij is ontvankelijk voor feedback, beschouwt de dag ook als een welkome uitnodiging om weer eens grondig naar zichzelf te kijken en ervan te leren.
  De heer Van der Corput scoort goed tot zeer goed op competenties als inlevingsvermogen, resultaatgerichtheid. Zijn gedragsflexibiliteit alsook zijn push (duwende) kanten van het beïnvloeden scoren sky high, wel waken voor de overdrijving.
  Er zijn natuurlijk ook de nodige ontwikkelpunten die we constateren. Veruit de meeste zijn ontwikkelbaar gelet op zijn aanleg (intelligentie, persoonlijkheid). Daarbij moet wel worden bedacht dat hij zich de nodige overlevingstechnieken en coping heeft moeten toe-eigenen als gevolg van zijn onveilige opvoeding. In zijn gedrag zien we hem soms worstelen en terugvallen op de vormen van afweermechanismes/coping. Immers, het kan voor hem, bewust of onbewust, wel eens als emotioneel onveilig voelen. Bijvoorbeeld zijn behoefte aan erkenning/serieus genomen, wordt gemakkelijk getriggerd.
  Het is bijzonder mooi om te merken hoe hij zich heeft ontwikkeld ondanks zijn nurture, en wat hij heeft bereikt en gepresteerd als volwassen man en ouder. Tegelijk is het onze aanbeveling bezig te blijven met het helen van oude wonden cq het voeden van wezenlijk vertrouwen in zichzelf; kwetsbaar te mogen zijn in plaats van geharnast.
  In dit rapport inclusief onze aanbevelingen focussen we op het verder ontwikkelen van vaardigheden/competenties op zakelijk (niet privé) vlak. Advies is om parallel hieraan ook met zijn persoonlijke ontplooiing verder aan de slag te gaan.
  Voor de heer Van der Corput geven wij meer specifieke ontwikkelpunten op de volgende competenties:
  Wat betreft analytische vaardigheid/oordeelsvorming in gesprekken mag de heer Van der Corput meer twijfelen aan zijn uitspraken in plaats van zich nog stelliger uit te spreken en te bluffen, met name bij tegenspel. Zulke stellige uitspraken heeft hij niet nodig om overeind te blijven of om de ander te overtuigen. Liever zien we dat hij zijn rust neemt, afstand neemt van de ander/materie, de context van een vraagstelling uitvoeriger in kaart brengt, doorvraagt bij onduidelijkheden en vooral waakt voor een te gemakkelijke/snelle oplossingen zonder eerst grondig te hebben geanalyseerd. Hiertoe heeft hij genoeg in huis qua intelligentie en talenten.
  Aangaande flexibiliteit mag hij ook bij inhoudelijk tegenspel soepel blijven manoeuvreren. Zoals hij in aan het begin van de gesprekken opereert: enthousiast, dynamisch en wendbaar. Maar als we de tegendruk opschroeven zien we dat hij zich groter maakt op allerlei manieren. Parool is om wat vaker te switchen van stijl. Push stijlen (zijn default) afwisselen met pull. Niet blokkeren of vechten als men het niet eens is met hem maar in plaats daarvan vragen te stellen waar de ander in zijn/haar opinie vandaan komt. Naar de onderliggende betekenis zoeken.
  Ten aanzien van overtuigingskracht adviseren we de heer Van der Corput om zijn gespreksgenoten meer te activeren in plaats van zichzelf te katapulteren, anderen aan het denken te zetten, meer aan te sluiten bij hun beweegredenen door middels vragen in te checken. Zich afvragen wat de ander motiveert of juist belemmert qua argumenten (Whats in it for me?). Ingaan op signalen van weerstand in plaats eroverheen te praten, bijvoorbeeld.
  Mogelijk kan wat coaching of training soelaas bieden. Gaarne doen we suggesties.
  Met zijn motivatie en instelling zien we hem de komende tijd verder doorgroeien in de rol van advocaat partner, zeker als hij bovenstaande adviezen in de praktijk brengt.`,
  
    example2: `Conclusie en advies
  Op basis van de resultaten tijdens het assessment center, de psychologische test en de interviews, komen wij tot de volgende conclusie.
  Mevrouw Van Bergen scoort op de meeste competenties voldoende tot goed, zoals: analytische vaardigheden, conceptueel vermogen, aspecten van inlevingsvermogen en leidinggeven, omgevingsbewustzijn en resultaatgerichtheid, waarbij zij bij deze laatste competentie mag waken voor een 'too much of a good thing.'
  We hebben haar over de dag heen leren kennen als een dynamische, intelligente, vriendelijke en ook sensitieve vrouw. Iemand met veel kwaliteiten in zowel de domeinen van voelen, denken en kracht. Haar uitdaging ligt wat ons betreft met name in de finetuning van deze drie, het uitbalanceren.
  Zo heeft zij namelijk zowel het presteren, als ook de kwaliteit van de relatie hoog in het vaandel, waardoor dit soms kan leiden tot een spanningsveld tussen deze twee. Aan de ene kant kan zij stevig duwen op haar doelen, terwijl ze aan de andere kant de relatie niet te veel onder druk wil zetten, met als gevolg dat haar aanpak soms overkomt als een vorm van remmend gasgeven.
  Er zitten in haar persoonlijkheid sowieso meer 'gasgevers' dan remmen. Zo heeft ze een verfrissende energie; ze is spontaan, heeft een jeugdig elan en is geregeld primair in haar reactie, waardoor ze soms ook wat minder bedachtzaam overkomt. Een slag om de arm houden of afgaan op haar secundaire ingevingen zal haar in de rol van bestuurder niet misstaan. Tevens kan ze in haar betrokkenheid zichzelf zeer sterk identificeren met haar rol en opdracht; waar dit aan de ene kant een kracht van haar is, kan het aan de andere kant haar ook extra kwetsbaar maken.
  Voor mevrouw Van Bergen geven wij meer specifieke ontwikkelpunten op de volgende competenties:
  Wat inlevingsvermogen betreft mag zij meer ingaan op de signalen die ze bij de ander waarneemt door deze te benoemen (gevoelsreflectie), uit te vragen en de achtergrond ervan te onderzoeken. Tevens mag zij haar eigen ingevingen en gevoelens toetsend inbrengen, waardoor ze sneller tot de kern van het gevoel bij de ander zal komen.
  Op het vlak van leidinggeven zien we de belangrijkste ontwikkeling op het vlak van relatiegericht leidinggeven. Zo kan zij de ander veel makkelijker in beweging krijgen op het moment dat ze aansluit op diens motivatie, drijfveren en ambitie. Tevens kan ze de ander meer aan het werk (en denken) zetten door deze te prikkelen met reflectieve vragen (coachen).
  Om haar onafhankelijkheid te vergroten mag zij in situaties die haar raken uit de interactie stappen en het proces benoemen. Tijd winnen, de bal terugkaatsen, benoemen wat er bij haar gebeurt of de ander aanspreken op gedrag. Het is met name belangrijk dat ze de rust in zichzelf hersteld voordat ze verder in de interactie stapt. Een meer beschouwende positie innemen zal haar helpen haar onafhankelijkheid te waarborgen.
  Als het om overtuigingskracht gaat dan mag zij meer ingaan op de behoefte van de persoon en diens vraag beantwoorden: 'What is in it for me?' Hierdoor kan ze haar argumenten op maat toesnijden, op wat de ander belangrijk en relevant vindt bijvoorbeeld.
  Al met al hebben wij veel vertrouwen in haar bestuurlijke capaciteiten, echter is onze indruk dat het rijpingsproces nog gaande is. Met haar reflectieve vermogen, leerbaarheid en leergierigheid verwachten wij desalniettemin dat zij deze rol met succes zal kunnen invullen.`,
  
    example3: `Conclusie en advies
  Op basis van de resultaten tijdens het assessment center, de psychologische test en de interviews, komen wij tot de volgende conclusie.
  De heer Sein maakt een sterk interactieve indruk, is een krachtige, sociaal-maatschappelijk bevlogen leider van mensen. Zijn persoonlijkheid laat veel aansluiting zien bij het onderhavige profiel. Datzelfde geldt voor zijn motivatie en cognitieve capaciteiten. Qua aanleg past hij goed in de onderhavige rol. Verder denken we dat verdere groei in bestuurlijke zin zeker tot de mogelijkheden behoort.
  Kijkend naar zijn competentieprofiel, zien we ook veel voldoende tot goed ontwikkelde vaardigheden. Hij is flexibel, resultaatgericht, heeft strategische visie en beschikt over goede analytische vaardigheid en oordeelsvorming. Hier en daar hebben we nog wat ontwikkeltips en adviezen gegeven (inlevingsvermogen, plannen en organiseren). Hier zit nog ontwikkelruimte.
  In hoge mate is de heer Sein gericht op samenwerking; sterker, op verbinding, met name met de bestuurder. Afstemming, erkenning, rugdekking, respect en ruimte in de samenwerking zijn cruciaal voor hem, voor verdere ontplooiing van zijn potentieel en effectiviteit . Het belang hiervan kan nauwelijks worden overschat. Vanuit een kwalitatief optimale afstemming is hij tot veel in staat. Daarom is het belang vanaf het begin te investeren in de onderlinge samenwerking.
  Dit is ons belangrijkste advies.`,
  }
  